/**
 * Spotify clone — static web player.
 *
 * Two sources of music:
 *   1. Your library — local albums listed in `songs.json`, generated by
 *      `scripts/generate-manifest.js`.
 *   2. Live search — the iTunes Search API, which is CORS-enabled and needs no
 *      API key, so it works from a purely static site. It returns 30-second
 *      Apple Music previews rather than full tracks.
 *
 * Everything is normalised into one queue shape:
 *   { title, subtitle, src, artwork? }
 * so playback, next/previous and the seek bar work identically for both.
 */

const MANIFEST_URL = "songs.json";
const ITUNES_ENDPOINT = "https://itunes.apple.com/search";
const SEARCH_LIMIT = 24;

const PLAY_ICON = "Images/play.svg";
const PAUSE_ICON = "Images/pause.svg";
const VOLUME_ICON = "Images/volume.svg";
const MUTE_ICON = "Images/mute.svg";

const PLAY_BADGE =
  "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='20' height='20' viewBox='0 0 64 64'><circle cx='32' cy='32' r='32' fill='%2322c55e'/><path fill='%23000' d='M42.4 32.5L23 44.38L22 45V20l1 .62z'/></svg>";

const NOTE_ICON = `<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" width="40" height="40" viewBox="0 0 24 24" style="color: rgb(174, 176, 179);"><path fill="currentColor" d="M8 6.1L19 5v11a3 3 0 0 1-3 3a3 3 0 0 1-3-3a3 3 0 0 1 3-3c.77 0 1.47.29 2 .76V9.04l-9 1V17a3 3 0 0 1-3 3a3 3 0 0 1-3-3a3 3 0 0 1 3-3c.77 0 1.47.29 2 .76zM9 7v2.03l9-.99V6.09zM8 17a2 2 0 0 0-2-2a2 2 0 0 0-2 2a2 2 0 0 0 2 2a2 2 0 0 0 2-2m10-1a2 2 0 0 0-2-2a2 2 0 0 0-2 2a2 2 0 0 0 2 2a2 2 0 0 0 2-2"></path></svg>`;

const audio = new Audio();
audio.preload = "metadata";

let albums = [];
let songs = [];
let currentAlbum = null;
let currentIndex = -1;
let lastVolume = 1;
let view = "library";

const seekbar = document.querySelector(".seekbar");
const circle = document.querySelector(".circle");
const playBtn = document.getElementById("play");
const previousBtn = document.getElementById("previous");
const nextBtn = document.getElementById("next");
const songInfo = document.querySelector(".songinfo");
const songTime = document.querySelector(".songtime");
const volumeSlider = document.querySelector(".range input");
const volumeIcon = document.querySelector(".volume > img");
const songListUl = document.querySelector(".songlist ul");
const cardContainer = document.querySelector(".cardcontainer");
const statusEl = document.getElementById("status");
const sectionTitle = document.getElementById("section-title");
const searchInput = document.getElementById("search-input");
const searchBtn = document.getElementById("search-btn");
const libraryBtn = document.getElementById("library-btn");

/* ------------------------------------------------------------------ utils */

function formatTime(seconds) {
  if (!Number.isFinite(seconds) || seconds < 0) return "00:00";
  const minutes = Math.floor(seconds / 60);
  const remaining = Math.floor(seconds % 60);
  return `${String(minutes).padStart(2, "0")}:${String(remaining).padStart(2, "0")}`;
}

/** Encode each path segment (track names contain spaces, parentheses, ...). */
function encodePath(filePath) {
  return filePath.split("/").map(encodeURIComponent).join("/");
}

function escapeHtml(value) {
  return String(value == null ? "" : value).replace(/[&<>"']/g, (char) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;",
  })[char]);
}

function showStatus(message) {
  if (!statusEl) return;
  statusEl.textContent = message || "";
  statusEl.hidden = !message;
}

/* ------------------------------------------------------- your own library */

async function loadManifest() {
  const response = await fetch(MANIFEST_URL, { cache: "no-cache" });
  if (!response.ok) {
    throw new Error(`Unable to load ${MANIFEST_URL} (HTTP ${response.status})`);
  }
  const data = await response.json();
  return Array.isArray(data.albums) ? data.albums : [];
}

function renderAlbumCards() {
  if (!albums.length) {
    cardContainer.innerHTML = `<p class="empty">No albums found.</p>`;
    return;
  }

  cardContainer.innerHTML = albums
    .map(
      (album) => `
      <div class="card" data-folder="${escapeHtml(album.folder)}" tabindex="0" role="button"
           aria-label="Open album ${escapeHtml(album.title)}">
        <div class="play"><img src="${PLAY_BADGE}" alt="" width="20" height="20"></div>
        ${album.cover ? `<img src="${encodePath(album.cover)}" alt="${escapeHtml(album.title)} cover" loading="lazy">` : ""}
        <h2>${escapeHtml(album.title)}</h2>
        <p>${escapeHtml(album.description)}</p>
      </div>`,
    )
    .join("");

  document.querySelectorAll(".card").forEach((card) => {
    const open = () => loadAlbum(card.dataset.folder);
    card.addEventListener("click", open);
    card.addEventListener("keydown", (event) => {
      if (event.key === "Enter" || event.key === " ") {
        event.preventDefault();
        open();
      }
    });
  });
}

async function loadAlbum(folder, { autoplay = false } = {}) {
  currentAlbum = albums.find((album) => album.folder === folder) || null;
  currentIndex = -1;
  view = "library";

  songs = currentAlbum
    ? currentAlbum.songs.map((song) => ({
        title: song.title,
        subtitle: currentAlbum.title,
        src: encodePath(song.path),
      }))
    : [];

  renderSongList();
  highlightCurrent();

  if (autoplay && songs.length) playMusic(0);
}

/* ---------------------------------------------------------- live search */

async function searchTracks(query) {
  const url = `${ITUNES_ENDPOINT}?term=${encodeURIComponent(query)}&media=music&entity=song&limit=${SEARCH_LIMIT}`;
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Search failed (HTTP ${response.status})`);

  const data = await response.json();
  return (data.results || [])
    // Tracks without a preview clip cannot be played at all, so drop them.
    .filter((item) => item.previewUrl)
    .map((item) => ({
      title: item.trackName || "Unknown track",
      subtitle: [item.artistName, item.collectionName].filter(Boolean).join(" · "),
      src: item.previewUrl,
      artwork: item.artworkUrl100 ? item.artworkUrl100.replace("100x100bb", "300x300bb") : null,
    }));
}

function renderTrackCards(tracks) {
  if (!tracks.length) {
    cardContainer.innerHTML = `<p class="empty">No playable songs found. Try a different search.</p>`;
    return;
  }

  cardContainer.innerHTML = tracks
    .map(
      (track, index) => `
      <div class="card track-card" data-index="${index}" tabindex="0" role="button"
           aria-label="Play ${escapeHtml(track.title)}">
        <div class="play"><img src="${PLAY_BADGE}" alt="" width="20" height="20"></div>
        ${track.artwork ? `<img src="${escapeHtml(track.artwork)}" alt="" loading="lazy">` : ""}
        <h2>${escapeHtml(track.title)}</h2>
        <p>${escapeHtml(track.subtitle)}</p>
      </div>`,
    )
    .join("");

  document.querySelectorAll(".track-card").forEach((card) => {
    const play = () => playMusic(Number(card.dataset.index));
    card.addEventListener("click", play);
    card.addEventListener("keydown", (event) => {
      if (event.key === "Enter" || event.key === " ") {
        event.preventDefault();
        play();
      }
    });
  });
}

function showLibrary() {
  view = "library";
  currentAlbum = null;
  songs = [];
  currentIndex = -1;
  sectionTitle.textContent = "Spotify Playlists";
  libraryBtn.hidden = true;
  showStatus("");
  renderSongList();
  renderAlbumCards();
}

function showSearchResults(tracks, query) {
  view = "search";
  currentAlbum = null;
  currentIndex = -1;
  songs = tracks;
  sectionTitle.textContent = `Results for “${query}”`;
  libraryBtn.hidden = false;
  renderSongList();
  renderTrackCards(tracks);
  highlightCurrent();
}

async function handleSearch(event) {
  if (event) event.preventDefault();

  const query = searchInput.value.trim();
  if (!query) {
    showLibrary();
    return;
  }

  searchBtn.disabled = true;
  showStatus(`Searching for “${query}”…`);

  try {
    const tracks = await searchTracks(query);
    if (!tracks.length) {
      showSearchResults([], query);
      showStatus(`No playable results for “${query}”. Try another search.`);
      return;
    }
    showSearchResults(tracks, query);
    // Be upfront that these are clips, not full tracks.
    showStatus("Playing 30-second Apple Music previews.");
  } catch (error) {
    console.error(error);
    showStatus("Search is unavailable right now. Please try again in a moment.");
  } finally {
    searchBtn.disabled = false;
  }
}

/* -------------------------------------------------------------- rendering */

function renderSongList() {
  songListUl.innerHTML = "";

  if (!songs.length) {
    songListUl.innerHTML = `<li class="empty">${
      view === "search" ? "Search for a song to see it here." : "This album has no songs yet."
    }</li>`;
    return;
  }

  songs.forEach((song, index) => {
    const li = document.createElement("li");
    li.dataset.index = index;
    li.innerHTML = `
      ${NOTE_ICON}
      <div class="Info">
        <div class="song-title">${escapeHtml(song.title)}</div>
        <div class="song-album">${escapeHtml(song.subtitle)}</div>
      </div>
      <div class="playnow"><img src="${PLAY_BADGE}" alt="" width="30" height="30"></div>`;
    li.addEventListener("click", () => playMusic(index));
    songListUl.appendChild(li);
  });
}

function highlightCurrent() {
  document.querySelectorAll(".songlist li").forEach((li) => {
    li.classList.toggle("active", Number(li.dataset.index) === currentIndex);
  });
  document.querySelectorAll(".track-card").forEach((card) => {
    card.classList.toggle("active", Number(card.dataset.index) === currentIndex);
  });
  document.querySelectorAll(".songlist li.empty").forEach((li) => li.classList.remove("active"));
}

/* -------------------------------------------------------------- playback */

function playMusic(index, { pause = false } = {}) {
  if (index < 0 || index >= songs.length) return;

  currentIndex = index;
  const song = songs[index];

  audio.src = song.src;

  songInfo.textContent = song.title;
  songTime.textContent = "00:00 / 00:00";
  circle.style.left = "0%";
  highlightCurrent();

  if (pause) {
    playBtn.src = PLAY_ICON;
    return;
  }

  audio
    .play()
    .then(() => {
      playBtn.src = PAUSE_ICON;
    })
    .catch(() => {
      // Browsers block autoplay until the visitor interacts.
      playBtn.src = PLAY_ICON;
      showStatus(`Tap play to start "${song.title}".`);
    });
}

function togglePlay() {
  if (!audio.src) {
    if (songs.length) playMusic(0);
    return;
  }

  if (audio.paused) {
    audio.play().then(() => (playBtn.src = PAUSE_ICON)).catch(() => {});
  } else {
    audio.pause();
    playBtn.src = PLAY_ICON;
  }
}

function step(offset) {
  if (!songs.length || currentIndex === -1) return;
  const next = currentIndex + offset;
  if (next < 0 || next >= songs.length) return;
  playMusic(next);
}

/* ------------------------------------------------------------------ setup */

function wireControls() {
  playBtn.addEventListener("click", togglePlay);
  previousBtn.addEventListener("click", () => step(-1));
  nextBtn.addEventListener("click", () => step(1));

  searchBtn.addEventListener("click", handleSearch);
  searchInput.addEventListener("keydown", (event) => {
    if (event.key === "Enter") handleSearch(event);
    if (event.key === "Escape") {
      searchInput.value = "";
      showLibrary();
    }
  });
  libraryBtn.addEventListener("click", showLibrary);

  audio.addEventListener("play", () => {
    playBtn.src = PAUSE_ICON;
  });

  audio.addEventListener("pause", () => {
    playBtn.src = PLAY_ICON;
  });

  audio.addEventListener("timeupdate", () => {
    if (!Number.isFinite(audio.duration)) return;
    songTime.textContent = `${formatTime(audio.currentTime)} / ${formatTime(audio.duration)}`;
    circle.style.left = `${(audio.currentTime / audio.duration) * 100}%`;
  });

  audio.addEventListener("ended", () => {
    if (currentIndex + 1 < songs.length) {
      playMusic(currentIndex + 1);
    } else {
      playBtn.src = PLAY_ICON;
      circle.style.left = "0%";
    }
  });

  audio.addEventListener("error", () => {
    showStatus("Sorry, that track could not be played.");
  });

  seekbar.addEventListener("click", (event) => {
    if (!Number.isFinite(audio.duration) || audio.duration === 0) return;
    const rect = seekbar.getBoundingClientRect();
    const percent = Math.min(100, Math.max(0, ((event.clientX - rect.left) / rect.width) * 100));
    circle.style.left = `${percent}%`;
    audio.currentTime = (audio.duration * percent) / 100;
  });

  volumeSlider.addEventListener("input", (event) => {
    const volume = Number(event.target.value) / 100;
    audio.volume = volume;
    lastVolume = volume;
    volumeIcon.src = volume === 0 ? MUTE_ICON : VOLUME_ICON;
  });

  volumeIcon.addEventListener("click", () => {
    if (audio.volume > 0) {
      lastVolume = audio.volume;
      audio.volume = 0;
      volumeSlider.value = 0;
      volumeIcon.src = MUTE_ICON;
    } else {
      const volume = lastVolume || 1;
      audio.volume = volume;
      volumeSlider.value = volume * 100;
      volumeIcon.src = VOLUME_ICON;
    }
  });

  document.querySelector(".hamburger").addEventListener("click", () => {
    document.querySelector(".left").style.left = "0";
  });

  document.querySelector(".close").addEventListener("click", () => {
    document.querySelector(".left").style.left = "-120%";
  });

  document.addEventListener("keydown", (event) => {
    const tag = event.target.tagName;
    if (tag === "INPUT" || tag === "TEXTAREA") return;
    if (event.code === "Space") {
      event.preventDefault();
      togglePlay();
    }
  });
}

async function main() {
  wireControls();

  audio.volume = 1;
  volumeSlider.value = 100;

  try {
    albums = await loadManifest();
    showLibrary();

    // Preload the first album's tracks into the queue without autoplaying
    // (autoplay is blocked until the visitor interacts with the page).
    if (albums.length) {
      await loadAlbum(albums[0].folder);
      if (songs.length) playMusic(0, { pause: true });
    } else {
      showStatus("No local albums found. Use search to play music.");
    }
  } catch (error) {
    console.error(error);
    showStatus("Could not load your local library. Live search still works.");
    cardContainer.innerHTML = `<p class="empty">Library unavailable — try searching above.</p>`;
  }

  // Deep link, e.g. /?q=coldplay — also makes searches shareable.
  const initialQuery = new URLSearchParams(window.location.search).get("q");
  if (initialQuery && initialQuery.trim()) {
    searchInput.value = initialQuery.trim();
    await handleSearch();
  }
}

main();
